# docker-compose build
version: '3.8'
volumes:
  pgdata:

services:

  db:
    build: .
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ./postgres.env
    ports:
      - 25432:5432
    restart: on-failure
    healthcheck:
      test: "exit 0"
     condition: service_healthy
